name1 = input('enter name name1 :')
name2 = input('enter name name2 :')
name3 = input('enter name name3 :')
name4 = input('enter name name4 :')
name5 = input('enter name name5 :')
name6 = input('enter name name6 :')
name7 = input('enter name name7 :')
name8 = input('enter name name8 :')
name9 = input('enter name name9 :')
name10 = input('enter name name10 :')
letter = input('enter one letter :')

name1 = name1.capitalize()
nqme2 = name2.capitalize()
name3 = name3.capitalize()
name4 = name4.capitalize()
name5 = name5.capitalize()
name6 = name6.capitalize()
name7 = name7.capitalize()
name8 = name8.capitalize()
name9 = name9.capitalize()
name10 = name10.capitalize()

n1 = name1.count(letter)
n2 = name2.count(letter)
n3 = name3.count(letter)
n4 = name4.count(letter)
n5 = name5.count(letter)
n6 = name6.count(letter)
n7 = name7.count(letter)
n8 = name8.count(letter)
n9 = name9.count(letter)
n10 = name10.count(letter)

print(name1,'>','count letter :',n1)
print(name2,'>','count letter :',n2)
print(name3,'>','count letter :',n3)
print(name4,'>','count letter :',n4)
print(name5,'>','count letter :',n5)
print(name6,'>','count letter :',n6)
print(name7,'>','count letter :',n7)
print(name8,'>','count letter :',n8)
print(name9,'>','count letter :',n9)
print(name10,'>','count letter :',n10)